package id.sisi.postoko.model

import android.os.Parcelable
import kotlinx.android.parcel.Parcelize

@Parcelize
data class GoodReceived(
    val alamat_shipto: String?,
//    val attachment: Any,
    val biller_id: String?,
    val company_code: String?,
    val company_name: String?,
    val created_at: String?,
    val distributor: String?,
    val distrik: String?,
    val ekspeditur: String?,
    val grand_total: String?,
    val id: String?,
    val incotrem: String?,
    val jam_antri: String?,
    val jam_masuk: String?,
    val jam_spj: String?,
    val kode_distributor: String?,
    val kode_distrik: String?,
    val kode_ekspeditur: String?,
    val kode_kecamatan: String?,
    val kode_plant: String?,
    val kode_produk: String?,
    val kode_shipto: String?,
    val line_so: String?,
    val nama_kapal: String?,
    val nama_kecamatan: String?,
    val nama_plant: String?,
    val nama_produk: String?,
    val nama_shipto: String?,
    val nama_sopir: String?,
    val no_do: String?,
//    val no_kontrak: Any,
    val no_polisi: String?,
    val no_pp: String?,
    val no_so: String?,
    val no_spj: String?,
    val no_spss: String?,
    val no_transaksi: String?,
    val nomer_po: String?,
//    val note: Any,
//    val order_discount: Any,
//    val order_discount_id: Any,
//    val order_tax: Any,
    val order_tax_id: String?,
    val product_discount: String?,
    val product_tax: String?,
    val qty_do: String?,
    val shipping: String?,
    val status: String?,
    val status_penerimaan: String?,
    val supplier_id: String?,
    val tanggal_antri: String?,
    val tanggal_do: String?,
    val tanggal_masuk: String?,
    val tanggal_pp: String?,
    val tanggal_so: String?,
    val tanggal_spj: String?,
    val tipe_order: String?,
    val total: String?,
    val total_discount: String?,
    val total_tax: String?,
    val uom: String?,
//    val updated_at: Any,
    val warehouse_id: String?
) : Parcelable {
    var good_received_items: List<PurchaseItem>? = arrayListOf()
}