package id.sisi.postoko.model

import android.os.Parcelable
import kotlinx.android.parcel.IgnoredOnParcel
import kotlinx.android.parcel.Parcelize

@Parcelize
data class GoodReceived(
    val alamat_shipto: String? = null,
//    val attachment: Any,
    val biller_id: String? = null,
    val company_code: String? = null,
    val company_name: String? = null,
    val created_at: String? = null,
    val distributor: String? = null,
    val distrik: String? = null,
    val ekspeditur: String? = null,
    val grand_total: String? = null,
    val id: String? = null,
    val incotrem: String? = null,
    val jam_antri: String? = null,
    val jam_masuk: String? = null,
    val jam_spj: String? = null,
    val kode_distributor: String? = null,
    val kode_distrik: String? = null,
    val kode_ekspeditur: String? = null,
    val kode_kecamatan: String? = null,
    val kode_plant: String? = null,
    val kode_produk: String? = null,
    val kode_shipto: String? = null,
    val line_so: String? = null,
    val nama_kapal: String? = null,
    val nama_kecamatan: String? = null,
    val nama_plant: String? = null,
    val nama_produk: String? = null,
    val nama_shipto: String? = null,
    val nama_sopir: String? = null,
    val no_do: String? = null,
//    val no_kontrak: Any,
    val no_polisi: String? = null,
    val no_pp: String? = null,
    val no_so: String? = null,
    val no_spj: String? = null,
    val no_spss: String? = null,
    val no_transaksi: String? = null,
    val nomer_po: String? = null,
//    val note: Any,
//    val order_discount: Any,
//    val order_discount_id: Any,
//    val order_tax: Any,
    val order_tax_id: String? = null,
    val product_discount: String? = null,
    val product_tax: String? = null,
    val qty_do: String? = null,
    val shipping: String? = null,
    val status: String? = null,
    val status_penerimaan: String? = null,
    val supplier_id: String? = null,
    val tanggal_antri: String? = null,
    val tanggal_do: String? = null,
    val tanggal_masuk: String? = null,
    val tanggal_pp: String? = null,
    val tanggal_so: String? = null,
    val tanggal_spj: String? = null,
    val tipe_order: String? = null,
    val total: String? = null,
    val total_discount: String? = null,
    val total_tax: String? = null,
    val uom: String? = null,
//    val updated_at: Any,
    val warehouse_id: String? = null
) : Parcelable {
    @IgnoredOnParcel
    var goodReceivedItems: List<PurchaseItem>? = arrayListOf()
}