package id.sisi.postoko.model

import android.os.Parcelable
import kotlinx.android.parcel.IgnoredOnParcel
import kotlinx.android.parcel.Parcelize

@Parcelize
data class Purchases(
    val id: Int,
    val reference_no: String,
    val date: String,
    val supplier_id: Int? = null,
    val supplier: String? = null,
    val warehouse_id: Int? = null,
    val note: String? = null,
    var total: Double?,
    val product_discount: Double? = null,
    val order_discount_id: Double? = null,
    val order_discount: Double? = null,
    val total_discount: Double? = null,
    val product_tax: Double? = null,
    val order_tax_id: Int? = null,
    val order_tax: Int? = null,
    val total_tax: Double? = null,
    var shipping: Double? = null,
    var grand_total: Double? = null,
    val paid: Double? = null,
    val status: String,
    val payment_status: String,
    val created_by: String? = null,
    val created_at: String? = null,
    val updated_by: String? = null,
    val updated_at: String? = null,
    var attachment: String? = null,
    var payment_term: Int? = 0,
    var due_date : String? = null,
    var return_id : String? = null,
    val surcharge : Double? = null,
    var return_purchase_ref : String? = null,
    var purchase_id : String? = null,
    var return_purchase_total : Double? = null,
    var client_id : String? = null,
    var flag : String? = null,
    var is_deleted : String? = null,
    var device_id : String? = null,
    var uuid : String? = null,
    var uuid_app : String? = null,
    var company_id : Int? = null,
    var company_head_id : Int? = null,
    var sino_spj: String? = null,
    var sino_do: String? = null,
    var sino_so: String? = null,
    var sino_billing: String? = null,
    var shipping_by: String? = null,
    var shipping_date: String? = null,
    var receiver: String? = null,
    var is_watched: Int? = null,
    var cf1: String? = null,
    var cf2: String? = null,
    var bank_id: Int? = null,
    var payment_method: String? = null,
    var payment_type: String? = null,
    var payment_deadline: String? = null,
    var payment_duration: String? = null,
    var charge : String? = null,
    var charge_third_party: String? = null,
    var third_party_sent_at: String? = null,
    var correction_price: String? = null,
    var delivery_method: String? = null,
    var license_plate: String? = null,
    var created_device: String? = null,
    var updated_device: String? = null
) : Parcelable {

    var purchaseItems: List<PurchaseItem>? = arrayListOf()
}