package id.sisi.postoko.model

import android.os.Parcelable
import kotlinx.android.parcel.IgnoredOnParcel
import kotlinx.android.parcel.Parcelize

@Parcelize
data class Sales (
    val id : Int,
    val date : String,
    val reference_no : String,
    val customer_id : Int? = null,
    val customer : String? = null,
    val biller_id : Int? = null,
    val biller : String? = null,
    val warehouse_id : Int? = null,
    val note : String? = null,
    val staff_note : String? = null,
    val total : Double? = null,
    val product_discount : Double? = null,
    val total_discount : Double? = null,
    var order_discount_id : String? = null,
    val order_discount : Double? = null,
    val product_tax : Double? = null,
    var order_tax_id : String? = null,
    val order_tax : Double? = null,
    val total_tax : Double? = null,
    val shipping : Double? = null,
    val grand_total : Double? = null,
    val sale_status : String,
    val payment_status : String? = null,
    val payment_term : Int? = null,
    val sale_type : String? = null,
    var due_date : String? = null,
    val created_by : String? = null,
    val created_at : String? = null,
    var updated_by : String? = null,
    var updated_at : String? = null,
    val total_items : Int? = null,
    val pos : Int? = null,
    val paid : Double? = null,
    var return_id : String? = null,
    val surcharge : Double? = null,
    val attachment : String? = null,
    var return_sale_ref : String? = null,
    var sale_id : String? = null,
    var return_sale_total : Double? = null,
    var rounding : String? = null,
    var client_id : String? = null,
    var flag : String? = null,
    var is_deleted : String? = null,
    var device_id : String? = null,
    var uuid : String? = null,
    var uuid_app : String? = null,
    var order_id : String? = null,
    var mtid : String? = null,
    var company_id : Int? = null,
    var delivery_date : String? = null,
    var is_updated_price : String? = null,
    var cf1 : String? = null,
    var cf2 : String? = null,
    var charge : String? = null,
    var reason : String? = null,
    var correction_price : String? = null,
    var delivery_method : String? = null,
    var payment_method : String? = null,
    var status_kredit_pro : String? = null,
    var delivery_status : String? = null
) : Parcelable {
    @IgnoredOnParcel
    var saleItems: List<SaleItem>? = arrayListOf()
}